### ISSUE TITLE
Организация кода

### ISSUE THREAD

**Issue by s9gf4ult** [DashaAntonova/csv#2]
Весь код написан в модуле `Main`. В хаскеле даже исполняемые программы выполняют
в форме библиотек, это даёт следующие приемущества

1. Пакет можно использовать как библиотеку, используя функции из него в своей
   программе.

2. Значительно упрощает тестирование. Код из библиотеки можно импортировать в
   тестах. Если код находится в исходниках исполняегого модуля, то импортировтаь
   его нельзя.

Смотри, в твоём `.cabal` файле есть секции

* `library` - тут описываются библиотечная часть пакета. Большинство пакетов на
  хакадже - именно библиотеки, и у них есть только эта секция + секция с
  тестами. Библиотечная часть описывает модули, которые будут доступны другим
  пакетам для импорта. Например, в твоей библитеке есть модуль `Lib`, если ты
  выложишь свой пакет на хакадж, то другой пользователь сможет добавить твой
  пакет в `build-depends` в своем `.cabal` файле и сделать `import Lib` своего
  модуля.

* `executable` - секция, описывающая исполняемую часть пакета. Обычно, в этой
  секции описывается единственный модуль `Main`, который долежн в идеале иметь
  очень маленькую функцию `main` вызывающую функции из библиотечной части. Часто
  в библиотечной части реализуют вообще всё, экспортируют функцию
  `defaultMain :: IO ()` которую и вызывает `main` в исполняемой части.

  Исполняемая часть может быть только одна в пакете. Если нужно несколько
  исполняемых файлов их оформляют отдельными пакетами. Это разумное ограничение,
  к тому же, `stack` может с одним `stack.yaml` собирать сразу много
  пакетов.

* `test-suite` - секция с тестами. Очень похожа на `executable` поскольку тоже
  описывает исполняемые модули, но `cabal/stack` работают с ними иначе. Их
  нельзя напрямую запустить через `stack exec`, но они запускаются при `stack
  test` при этом есть специальные механизмы для сбора результатов тестов.  В
  пакете может быть несколько секций `test-suite`.

  Часто, в виде тестов оформляют примеры использования библиотек. Это позволяет
  проверять, что примеры рабочие. Бывает полезно смотреть в исходный код
  библиотек по этой причине.

Обрати внимание, что в каждой секции есть свои `build-depends`, когда будешь
переносить код в библиотеку тебе надо будет все зависимости перенести именно
туда, исполняемая часть будет зависеть только от библиотеки `csv`,
т.е. библиотеки твоего пакета.

Пример организации кода можешь посмотреть https://github.com/s9gf4ult/burn

**Comment by DashaAntonova** [comment]
Создала библиотеку, в Main сейчас вызываются функции.
