### ISSUE TITLE
Функция `func`

### ISSUE THREAD

**Issue by s9gf4ult** [DashaAntonova/csv#4]
Итак, что делает эта функция:

1. Разбивает текст на куски, разделенные запятыми
2. Создает кортеж из первых двух элементов, плюс отдельно первый элемент с
   применённой к нему `read`

Тут есть следующие проблемы

* Функция выполняет слишком много работы одновременно, от чего очень запутанная
  и трудно понимаемая. Попробуй разбить её на две функции, а потом
  скомбинировать их. В хаскеле программы обычно пишутся комбинированием сложных
  функций из простых. В данном случае у тебя должно получиться две функции с
  такими типами: `split: Char -> Text -> [Text]` и
  `getDate :: [Text] -> (Text, Text, DateTime)`

    * Спойлер: функция `split` уже есть в пакете `text`
      http://hackage.haskell.org/package/text-1.2.2.0/docs/Data-Text.html#g:18
      но в целях обучения её лучше написать самостоятельно. `groupBy` лучше не
      использовать, попробуй написать функцию через `foldl` либо сделать
      рекурсивную функцию.

      В хаскеле рекурсивные функции как правило не приводят к переполнению
      стека за счёт ленивости. Функции с хвостовой рекурсией к вообще
      гарантированно не заполняют стек.

* Фукнция применяется для парсинга CSV, но CSV это не просто строчки резделенные
  запятыми, там есть еще строки в кавычках, которые применяются для хранения
  строк, которые содержат запятую и/или кавычки. Полноценный парсинг CSV
  значительно более сложный, чем просто разбить по запятой. Именно по этой
  причине я предложил изначально взять `cassava`.

*  Функция имеет не понятный тип. В хаскеле под всё заводить новые типы
   данных. Это уменьшает вероятность ошибок и значительно повышает читабельность
   кода. Тип `(Text, Text, DateTime)` удобен для записи, но абсолютно не читаем
   для человека, не писавшего этот код. Смотри на сколько увеличивается
   понятность кода если переписать

   ```haskell
   data CSVREcord = CSVREcord
     { crField0 :: DateTime
     , crField1 :: Text
     } deriving (Ord, Eq, Show)

   func :: T.Text -> CSVREcord
   func str = CSVREcord
     { crField0 = fromSeconds (read (T.unpack (zFilter !! 0)))
     , crField1 = zFilter !! 1 }
     where
       zFilter = filter (\x -> if x /= T.pack (",") then True else False) z
       z = T.groupBy (\x y -> if (x /= ',' && y /= ',') then True else False) str
   ```

   Из типа сразу напрашивается более понятно имя для `func`

*   Функция `func` может выбрасывать исключения. В хаскеле считается хорошим
    тоном выбрасывать исключения только в `IO`, а в чистом коде отражать
    исключения в типах, и прерывать вычисление с помощью монад.

    Смотри, в твоей функции используется оператор `(!!)`, вот что произойдет,
    если вызвать его с не правильными аргументами:

    ```haskell
    > [1] !! 1
    *** Exception: Prelude.!!: index too large
    ```

    Эти исключения очень не удобно отлавливать, кроме того, хаскель - язык с
    ленивыми вычислениями, это значит, что функция может вернуть результат,
    который не до конца вычислен.

    ```haskell
    Prelude Lib Main> let [a, b] = [[1] !! 0, [1] !! 1]
    Prelude Lib Main> a
    1
    Prelude Lib Main> b
    *** Exception: Prelude.!!: index too large
    ```

    Обрати внимание, что в первой строке вычислились только конструкторы списка,
    а значения, лежащие в списке не вычислились. Но когда мы просим
    интерпретатор показать результаты, он их вычисляет, и получает ошибку. Это
    плата за нестрогий порядок вычислений, который взмен даёт много других
    возможностей.

    В языках с нестрогими вычислениями фактический порядок вычислений аргументов
    функций может сильно отличаться от языков со строгими вычислениями, по
    этому, в чистом коде лучше писать код, который не выбрасывает исключений,
    ведь их отлавливать сложнее, чем в строгих языках.

    ```haskell
    Prelude Lib Control.Exception> [a, b] <- catch (return [[1] !! 0, [1] !! 1]) (\(_ :: SomeException) -> return [])
    Prelude Lib Control.Exception> a
    1
    Prelude Lib Control.Exception> b
    *** Exception: Prelude.!!: index too large
    ```

    Обрати внимание, что `catch` тут не поймала исключение, поскуольку
    вычисление до выброса исключения просто не дошло.

    *  Спойлер: на самом деле эта проблема тоже давно решена, у нас есть пакет
       `deepseq` который позволяет управлять порядком вычислений:

       ```haskell
       Prelude Lib Control.Exception Control.DeepSeq Main> a <- catch (return $!! [[1] !! 0, [1] !! 1]) (\(e :: SomeException) -> print e >> return [])
       Prelude.!!: index too large
       Prelude Lib Control.Exception Control.DeepSeq Main> a
       []
       ```

       Теперь функция `catch` поймала исключение. Обработчик его распечатал, а
       результат - пустой список, который вернул обработчик. Это произошло
       потому, что оператор `($!!)` форсировал вычисление списка вместе со всем
       его содержимым. Таким образом можно гаранитировать отсутствие
       исключений, но это скорее костыль, чем правильное решение.

    В данном случае ты можешь использовать монаду `Maybe`

    ```haskell
    import Safe

    func :: T.Text -> Maybe (T.Text, T.Text, DT.DateTime)
    func str = do
      f1 <- atMay zFilter 0
      f2 <- atMay zFilter 1
      int <- readMay $ T.unpack f1
      let f3 = DT.fromSeconds int
      return (f1, f2, f3)
      where
        zFilter = filter (\x -> if x /= T.pack (",") then True else False) z
        z = T.groupBy (\x y -> if (x /= ',' && y /= ',') then True else False) str
    ```

    К сожалению, в стандартной библиотеке нет многих безопасных функций, она
    писалась очень давно, и тогда о подобных проблемах не знали. Для безопасной
    работы со стандартными типами есть пакет `safe`, из которого я взял функции
    `atMay` и `readMay`.

    ```haskell
    Prelude Lib Main> func "asdf"
    Nothing
    Prelude Lib Main> func "asdf,asdf"
    Nothing
    Prelude Lib Main> func "12341234,asdf"
    Just ("12341234","asdf",1970-05-23 20:07:14 UTC)
    ```

    Теперь функция не выбрасывает исключений, и если она вернула `Just` то там
    гарантированно вычисленный кортеж.

**Comment by DashaAntonova** [comment]
Я могу закрыть этот ишус? Функции func у меня уже нет, и с cassava я постепенно общаюсь

**Comment by s9gf4ult** [comment]
Да
